nodeLinker: node-modules

npmScopes:
  fortawesome:
    npmAlwaysAuth: true
    npmRegistryServer: 'https://npm.fontawesome.com/'
    npmAuthToken: '274CBC58-42FC-486B-87EF-53343405535E'
  awesome.me:
    npmAlwaysAuth: true
    npmRegistryServer: 'https://npm.fontawesome.com/'
    npmAuthToken: '274CBC58-42FC-486B-87EF-53343405535E'

yarnPath: .yarn/releases/yarn-4.9.2.cjs
